# Dockerfile for Debian with basic tools
FROM debian:latest

# Install some basic tools (optional)
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    vim \
    git \
    ssh

CMD ["/bin/bash"]
